version: '3'

services:

  ####### Development and Test Environment #######

  metalpolis-db:
    build: 
      context: ./mysql
    environment:
      DB_USER: metal_dbuser
      DB_PASS: vackertech2018
      DB_NAME: metalpolis_database
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      DB_IMPORT_FILE: /home/dbsetup.sql
    hostname: metalpolis-db
    ports:
      - 3306:3306
    # volumes:
    #   - "./mysql/data:/var/lib/mysql:rw"
  
  metalpolis-web:
    build: 
      context: .
    volumes:
      #- "./www:/home/metalpolis/web:rw"
      - "./www:/var/www/site:rw"
      - "./php.ini:/etc/php/7.0/cli/php.ini"
      #- ${PWD}/php.ini:/etc/php/7.0/cli/php.ini
    hostname: metalpolis-web
    ports:
      - 8080:80
    links:
      - metalpolis-db
    depends_on:
      - metalpolis-db
    # networks:
    #   driver: host


  ####### Production Environment #######
    # metalpolis-web:
    #   build: 
    #     context: .
    #   volumes:
    #     - "./www:/var/www/site:rw"
    #     - "./php.ini:/etc/php/7.0/cli/php.ini"
    #   hostname: metalpolis-web
    #   ports:
    #     - 80:80
    
  
  
  